#---------------------------
# Material-T
# 一个基于Material Design风格的主题
# Author: invom
# Github: https://github.com/invom/Material-T
#---------------------------


#---------------------------
#站点信息
#Site Infomation
#---------------------------
if_subtitle: true
index_top_pic: 

#---------------------------
#导航栏
#Top Navbar
#---------------------------
if_nav: true


if_menu: true
menu:
  #Home: /
  archives: /archives/
  #Projects: /projects/
  about: /about/
  

if_social_icons: true
social_icons: 
  github: 
  #Facebook: 
  twitter:
  telegram:
  #Weibo: 
  

#---------------------------
#文章页
#Post Page
#---------------------------
toc: true



#---------------------------
#关于页
#About Page
#---------------------------
about:
  avatar: 
  name: 
  job:  
  introduce: 
  extension: # 留空供大佬们自由发挥

about_icons: 
  facebook: https://facebook.com
  weibo: https://weibo.com
  weixin: 


#---------------------------
#底部信息
#footer
#---------------------------
footer: <a href="https://hexo.io/zh-cn/">HEXO</a>