#---------------------------
# Fluid
# Author: Fluid-dev organization
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#---------------------------


#---------------------------
# 全局
# Site
#---------------------------
favicon: /img/favicon.png # 网站标签页的 icon

apple_touch_icon: /img/apple-touch-icon.png # 用于苹果设备的 icon

title_join_string: ' ~ '  # 浏览器标签页中的标题分隔符，效果： 文章名 ~ 站点名

source_base_path: / # 静态资源目录，如使用 OSS 或 CDN（需要开启跨域），可修改成 url，其他非特殊情况请保持默认

highlight: # 代码高亮
  enable: true
  theme: tomorrow-night-eighties # available: github-v2 | tomorrow | tomorrow-night | tomorrow-night-eighties，更多主题可从 https://jmblog.github.io/color-themes-for-google-code-prettify/ 获取，保存为 `*.min.css` 到 `source/lib/prettify/`，在其中 .prettyprint{ background: ***; ...} 的background 值后加上 !important，例如：.prettyprint{background:#fafbfc!important; ...}

fun_features: # 一些好玩的功能
  typing: # 为 subtitle 添加打字机效果
    enable: true
    typeSpeed: 70 # 打印速度
    cursorChar: "_" # 游标字符
    loop: false # 是否循环播放效果
  anchorjs: # 为文章内容中的标题添加锚图标
    enable: true
    element: h1,h2,h3,h4,h5,h6
    placement: right # icon放置的位置： left | right
    visible: false # true：一直可见，false：鼠标悬停时出现
    icon: "" # 例如：§ | # | ❡ 等，留空则为默认效果

color:  # 主体颜色配置，可以从这里寻找启发： https://www.webdesignrankings.com/resources/lolcolors/
  body-bg-color: "#eee"
  navbar-bg-color: "#2f4154"
  navbar-text-color: "white"
  text-color: "#3c4858"
  link-color: "#3c4858"
  link-hover-color: "#1abc9c"

search: # 搜索栏
  enable: true
  path: /local-search.xml
  field: post
  content: true

baidu_analytics:  # 百度统计的Key


#---------------------------
# 导航栏
# Head Navbar
#---------------------------
navbar:
  blog_title:  # 导航栏左侧的标题，为空则按 hexo config.title 显示
  menu:
    Home: /
    Archives: /archives/
    Categories: /categories/
    Tags: /tags/
    About: /about/


#---------------------------
# 页脚
# Footer
#---------------------------
footer:
  beian:  # The footer of China's website policy, other areas keep disable
    enable: false
    icp_text: 京ICP证123456号 # ICP证号
    police_text: 京公网安备12345678号 # 公安备案号，不填则只显示ICP
    police_code: 12345678 # 公安备案的编号，用于URL跳转查询


#---------------------------
# 首页
# Index Page
#---------------------------
index:
  banner_img: /img/index.jpg
  banner_img_height: 100  # available: 0 - 100
  slogan:  # 首页副标题的独立设置
    enable: true  # 为 false 则不显示任何内容
    text:  # 为空则按 hexo config.subtitle 显示
  auto_excerpt:
    enable: true
  post_url_target: _self  # available: _blank | _self
  post_meta: # 是否显示文章信息（时间、分类、标签）
    date: true
    category: true
    tag: true


#---------------------------
# 文章页
# Post Page
#---------------------------
post: 
  banner_img: /img/post.jpg
  banner_img_height: 70  # available: 0 - 100
  date_format: "dddd, MMMM Do YYYY, h:mm a"
  toc: 
    enable: true
  copyright:
    enable: true
    content: '本博客所有文章除特别声明外，均采用 <a href="https://zh.wikipedia.org/wiki/Wikipedia:CC_BY-SA_3.0%E5%8D%8F%E8%AE%AE%E6%96%87%E6%9C%AC" rel="nofollow noopener">CC BY-SA 3.0协议</a> 。转载请注明出处！'
  custom:
    enable: false
    content: '<img src="https://octodex.github.com/images/jetpacktocat.png" class="rounded mx-auto d-block mt-5" style="width:150px; height:150px;">' # 自定义区域，支持 HTML，可自行插入赞赏码、公众号二维码等内容
  comments: 
    enable: false
    type: disqus  # available: disqus | valine | gitalk | utterances


#---------------------------
# 评论
# Comments
#---------------------------

# utterances 
# You can install utterances with https://utteranc.es/ and generate your configuration
utterances:
  repo:
  issue_term:
  label: utterances
  theme: github-light
  crossorigin: anonymous

# Disqus
disqus:
  shortname: # your shortname

# Gitalk
# You can get yout ClientID and ClientSecret from https://github.com/settings/applications/new
# More info available at https://github.com/gitalk/gitalk#options
gitalk:
  clientID:                     # GitHub Application Client ID
  clientSecret:                 # GitHub Application Client Secret
  repo:                         # The repo to store comments
  owner:                        # GitHub repository owner. Can be personal user or organization.
  admin:                        # GitHub repo owner and collaborators, only these guys can initialize github issues, should be like "['admin']" or "['admin1','admin2']"
  id: location.pathname         # The unique id of the page. Length must less than 50.
  language: zh-CN               # Localization language key, en, zh-CN and zh-TW are currently available.
  labels: "['Gitalk']"          # GitHub issue labels.
  perPage: 15                   # Pagination size, with maximum 100.
  pagerDirection: last          # Comment sorting direction, available values are last and first.
  distractionFreeMode: false    # Facebook-like distraction free mode.
  createIssueManually: true     # By default, Gitalk will create a corresponding github issue for your every single page automatically when the logined user is belong to the admin users. You can create it manually by setting this option to true.

# Valine
# You can get your appid and appkey from https://leancloud.cn
# More info available at https://valine.js.org
valine:
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier, See: https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: 说点什么 # comment box placeholder
  avatar: retro # gravatar style https://valine.js.org/avatar.html
  pageSize: 10 # pagination size
  visitor: false # leancloud-counter-security is not supported for now. When visitor is set to be true, appid and appkey are recommended to be the same as leancloud_visitors' for counter compatibility. Article reading statistic https://valine.js.org/visitor.html


#---------------------------
# 归档页
# Archive Page
#---------------------------
archive:
  banner_img: /img/archive.jpg
  banner_img_height: 80  # available: 0 - 100


#---------------------------
# 分类归档页
# Categories Page
#---------------------------
category:
  banner_img: /img/archive.jpg
  banner_img_height: 80  # available: 0 - 100


#---------------------------
# 标签归档页
# Tags Page
#---------------------------
tag:
  banner_img: /img/archive.jpg
  banner_img_height: 80  # available: 0 - 100
  tagcloud: # 标签云
    min_font: 15
    max_font: 30
    unit: px  # 字号单位
    start_color: "#BBBBEE"
    end_color: "#337ab7"


#---------------------------
# 关于页
# About Page
#---------------------------
about:  # 以下仅为页面顶部的基本信息，更多内容请在 ./pages/about.md 中编辑，支持 markdown 和 HTML
  banner_img: /img/about.jpg
  banner_img_height: 80  # available: 0 - 100
  avatar: /img/avatar.png # 头像
  name: myname
  introduce: info / info / info # 支持 HTML
  icons: # 更多图标可从 https://fontawesome.com/icons 查找，并以 "图标名: url" 的格式添加在下方
    "fab fa-github": https://github.com
    "fab fa-twitter": https://twitter.com


#---------------------------
# 404页
# 404 Page
#---------------------------
page404:
  banner_img: /img/index.jpg
  banner_img_height: 80  # available: 0 - 100
  subtitle: 'Page not found'